"""File for keeping all global constants."""

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
TICK_RATE = 60

BACKGROUND_WIDTH = 1200
BACKGROUND_HEIGHT = 600

NUM_OF_ENEMIES = 10
TIME_BETWEEN_ENEMIES = 1000
ENEMY_SPEED = 3

BACKGROUND_SPEED = 1
PLAYER_SPEED = 5

MUSIC_FILENAME = "assets/8bitmusic.mp3"
ENEMY_FILENAME = "assets/Enemy_Player.png"
PLAYER_FILENAME = "assets/UNC_Player.png"
BACKGROUND_FILENAME = "assets/FootballField.jpg"